{
 "title": "API Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Response Code Summary",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "response_code_summary_count", "legendFormat": "{{status_code}}" }
   ]
  },
  {
   "title": "Request Duration in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "request_duration_seconds_bucket",
     "legendFormat": "{{method}}: {{status_code}}. Time Taken: {{le}}s"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    { "expr": "total_requests", "legendFormat": "Total Requests" }
   ]
  }
 ]
}